class INTERPOLATION:
    """Constant, No interpolation, value of A gets held until B is encountered"""

    CONSTANT = "CONSTANT"
    """Linear, Straight-line interpolation between A and B (i.e. no ease in/out)"""
    LINEAR = "LINEAR"
    """Bezier, Smooth interpolation between A and B, with some control over curve shape"""
    BEZIER = "BEZIER"
    """Sinusoidal, Sinusoidal easing (weakest, al
    most linear but with a slight curvature)"""
    SINE = "SINE"
    """Quadratic, Quadratic easing"""
    QUAD = "QUAD"
    """Cubic, Cubic easing"""
    CUBIC = "CUBIC"
    """Quartic, Quartic easing"""
    QUART = "QUART"
    """Quintic, Quintic easing"""
    QUINT = "QUINT"
    """Exponential, Exponential easing (dramatic)"""
    EXPO = "EXPO"
    """Circular, Circular easing (strongest and most dynamic)"""
    CIRC = "CIRC"
    """Back, Cubic easing with overshoot and settle"""
    BACK = "BACK"
    """Bounce, Exponentially decaying parabolic bounce, like when objects collide"""
    BOUNCE = "BOUNCE"
    """Elastic"""
    ELASTIC = "ELASTIC"

    ALL_ = [
        CONSTANT,
        LINEAR,
        BEZIER,
        SINE,
        QUAD,
        CUBIC,
        QUART,
        QUINT,
        EXPO,
        CIRC,
        BACK,
        BOUNCE,
        ELASTIC,
    ]


class KEYFRAME:
    """Keyframe, Normal keyframe, e.g. for key poses."""

    KEYFRAME = "KEYFRAME"

    """Breakdown, A breakdown pose, e.g. for transitions between key poses."""
    BREAKDOWN = "BREAKDOWN"

    """Moving Hold, A keyframe that is part of a moving hold."""
    MOVING_HOLD = "MOVING_HOLD"

    """Extreme, An ‘extreme’ pose, or some other purpose as needed."""
    EXTREME = "EXTREME"

    """Jitter, A filler or baked keyframe for keying on ones, or some other purpose as needed."""
    JITTER = "JITTER"

    ALL_ = [KEYFRAME, BREAKDOWN, MOVING_HOLD, EXTREME, JITTER]


class units:
    NONE = "NONE"
    LENGTH = "LENGTH"
    AREA = "AREA"
    VOLUME = "VOLUME"
    ROTATION = "ROTATION"
    TIME = "TIME"
    VELOCITY = "VELOCITY"
    ACCELERATION = "ACCELERATION"
    MASS = "MASS"
    CAMERA = "CAMERA"
    POWER = "POWER"

    ALL_ = [
        NONE,
        LENGTH,
        AREA,
        VOLUME,
        ROTATION,
        TIME,
        VELOCITY,
        ACCELERATION,
        MASS,
        CAMERA,
        POWER,
    ]


class subtype_numeric:
    NONE = "NONE"
    PIXEL = "PIXEL"
    UNSIGNED = "UNSIGNED"
    PERCENTAGE = "PERCENTAGE"
    FACTOR = "FACTOR"
    ANGLE = "ANGLE"
    TIME = "TIME"
    DISTANCE = "DISTANCE"
    DISTANCE_CAMERA = "DISTANCE_CAMERA"
    POWER = "POWER"
    TEMPERATURE = "TEMPERATURE"

    ALL_ = [
        NONE,
        PIXEL,
        UNSIGNED,
        PERCENTAGE,
        FACTOR,
        ANGLE,
        TIME,
        DISTANCE,
        DISTANCE_CAMERA,
        POWER,
        TEMPERATURE,
    ]


class subtype_string:
    FILE_PATH = "FILE_PATH"
    DIR_PATH = "DIR_PATH"
    FILE_NAME = "FILE_NAME"
    BYTE_STRING = "BYTE_STRING"
    PASSWORD = "PASSWORD"
    NONE = "NONE"

    ALL_ = [
        FILE_PATH,
        DIR_PATH,
        FILE_NAME,
        BYTE_STRING,
        PASSWORD,
        NONE,
    ]


class subtype_vector:
    NONE = "NONE"
    COLOR = "COLOR"
    TRANSLATION = "TRANSLATION"
    DIRECTION = "DIRECTION"
    VELOCITY = "VELOCITY"
    ACCELERATION = "ACCELERATION"
    MATRIX = "MATRIX"
    EULER = "EULER"
    QUATERNION = "QUATERNION"
    AXISANGLE = "AXISANGLE"
    XYZ = "XYZ"
    XYZ_LENGTH = "XYZ_LENGTH"
    COLOR_GAMMA = "COLOR_GAMMA"
    COORDINATES = "COORDINATES"
    LAYER = "LAYER"
    LAYER_MEMBER = "LAYER_MEMBER"

    ALL_ = [
        NONE,
        COLOR,
        TRANSLATION,
        DIRECTION,
        VELOCITY,
        ACCELERATION,
        MATRIX,
        EULER,
        QUATERNION,
        AXISANGLE,
        XYZ,
        XYZ_LENGTH,
        COLOR_GAMMA,
        COORDINATES,
        LAYER,
        LAYER_MEMBER,
    ]


class constraints:
    COPY_LOCATION = "COPY_LOCATION"
    COPY_ROTATION = "COPY_ROTATION"
    COPY_SCALE = "COPY_SCALE"
    LIMIT_DISTANCE = "LIMIT_DISTANCE"
    LIMIT_LOCATION = "LIMIT_LOCATION"
    LIMIT_ROTATION = "LIMIT_ROTATION"
    LIMIT_SCALE = "LIMIT_SCALE"
    TRANSFORM = "TRANSFORM"
    DAMPED_TRACK = "DAMPED_TRACK"
    IK = "IK"
    STRETCH_TO = "STRETCH_TO"
    CHILD_OF = "CHILD_OF"
    PIVOT = "PIVOT"
    SHRINKWRAP = "SHRINKWRAP"

    ALL_ = [
        COPY_LOCATION,
        COPY_ROTATION,
        COPY_SCALE,
        LIMIT_DISTANCE,
        LIMIT_LOCATION,
        LIMIT_ROTATION,
        LIMIT_SCALE,
        TRANSFORM,
        DAMPED_TRACK,
        IK,
        STRETCH_TO,
        CHILD_OF,
        PIVOT,
        SHRINKWRAP,
    ]


class icons:
    ACTION = "ACTION"
    ACTION_TWEAK = "ACTION_TWEAK"
    ADD = "ADD"
    ALIASED = "ALIASED"
    ALIGN_BOTTOM = "ALIGN_BOTTOM"
    ALIGN_CENTER = "ALIGN_CENTER"
    ALIGN_FLUSH = "ALIGN_FLUSH"
    ALIGN_JUSTIFY = "ALIGN_JUSTIFY"
    ALIGN_LEFT = "ALIGN_LEFT"
    ALIGN_MIDDLE = "ALIGN_MIDDLE"
    ALIGN_RIGHT = "ALIGN_RIGHT"
    ALIGN_TOP = "ALIGN_TOP"
    ANCHOR_BOTTOM = "ANCHOR_BOTTOM"
    ANCHOR_CENTER = "ANCHOR_CENTER"
    ANCHOR_LEFT = "ANCHOR_LEFT"
    ANCHOR_RIGHT = "ANCHOR_RIGHT"
    ANCHOR_TOP = "ANCHOR_TOP"
    ANIM = "ANIM"
    ANIM_DATA = "ANIM_DATA"
    ANTIALIASED = "ANTIALIASED"
    APPEND_BLEND = "APPEND_BLEND"
    ARMATURE_DATA = "ARMATURE_DATA"
    ARROW_LEFTRIGHT = "ARROW_LEFTRIGHT"
    ASSET_MANAGER = "ASSET_MANAGER"
    AUTO = "AUTO"
    AUTOMERGE_OFF = "AUTOMERGE_OFF"
    AUTOMERGE_ON = "AUTOMERGE_ON"
    AXIS_FRONT = "AXIS_FRONT"
    AXIS_SIDE = "AXIS_SIDE"
    AXIS_TOP = "AXIS_TOP"
    BACK = "BACK"
    BLANK1 = "BLANK1"
    BLENDER = "BLENDER"
    BOIDS = "BOIDS"
    BOLD = "BOLD"
    BONE_DATA = "BONE_DATA"
    BOOKMARKS = "BOOKMARKS"
    BORDERMOVE = "BORDERMOVE"
    BRUSHES_ALL = "BRUSHES_ALL"
    BRUSH_BLOB = "BRUSH_BLOB"
    BRUSH_BLUR = "BRUSH_BLUR"
    BRUSH_CLAY = "BRUSH_CLAY"
    BRUSH_CLAY_STRIPS = "BRUSH_CLAY_STRIPS"
    BRUSH_CLONE = "BRUSH_CLONE"
    BRUSH_CREASE = "BRUSH_CREASE"
    BRUSH_DATA = "BRUSH_DATA"
    BRUSH_FILL = "BRUSH_FILL"
    BRUSH_FLATTEN = "BRUSH_FLATTEN"
    BRUSH_GRAB = "BRUSH_GRAB"
    BRUSH_INFLATE = "BRUSH_INFLATE"
    BRUSH_LAYER = "BRUSH_LAYER"
    BRUSH_MASK = "BRUSH_MASK"
    BRUSH_MIX = "BRUSH_MIX"
    BRUSH_NUDGE = "BRUSH_NUDGE"
    BRUSH_PINCH = "BRUSH_PINCH"
    BRUSH_ROTATE = "BRUSH_ROTATE"
    BRUSH_SCRAPE = "BRUSH_SCRAPE"
    BRUSH_SCULPT_DRAW = "BRUSH_SCULPT_DRAW"
    BRUSH_SMEAR = "BRUSH_SMEAR"
    BRUSH_SMOOTH = "BRUSH_SMOOTH"
    BRUSH_SNAKE_HOOK = "BRUSH_SNAKE_HOOK"
    BRUSH_SOFTEN = "BRUSH_SOFTEN"
    BRUSH_TEXDRAW = "BRUSH_TEXDRAW"
    BRUSH_TEXFILL = "BRUSH_TEXFILL"
    BRUSH_TEXMASK = "BRUSH_TEXMASK"
    BRUSH_THUMB = "BRUSH_THUMB"
    CAMERA_DATA = "CAMERA_DATA"
    CAMERA_STEREO = "CAMERA_STEREO"
    CANCEL = "CANCEL"
    CENTER_ONLY = "CENTER_ONLY"
    CHECKBOX_DEHLT = "CHECKBOX_DEHLT"
    CHECKBOX_HLT = "CHECKBOX_HLT"
    CHECKMARK = "CHECKMARK"
    CLIPUV_DEHLT = "CLIPUV_DEHLT"
    CLIPUV_HLT = "CLIPUV_HLT"
    COLLAPSEMENU = "COLLAPSEMENU"
    COLLECTION_COLOR_01 = "COLLECTION_COLOR_01"
    COLLECTION_COLOR_02 = "COLLECTION_COLOR_02"
    COLLECTION_COLOR_03 = "COLLECTION_COLOR_03"
    COLLECTION_COLOR_04 = "COLLECTION_COLOR_04"
    COLLECTION_COLOR_05 = "COLLECTION_COLOR_05"
    COLLECTION_COLOR_06 = "COLLECTION_COLOR_06"
    COLLECTION_COLOR_07 = "COLLECTION_COLOR_07"
    COLLECTION_COLOR_08 = "COLLECTION_COLOR_08"
    COLLECTION_NEW = "COLLECTION_NEW"
    COLOR = "COLOR"
    COLORSET_01_VEC = "COLORSET_01_VEC"
    COLORSET_02_VEC = "COLORSET_02_VEC"
    COLORSET_03_VEC = "COLORSET_03_VEC"
    COLORSET_04_VEC = "COLORSET_04_VEC"
    COLORSET_05_VEC = "COLORSET_05_VEC"
    COLORSET_06_VEC = "COLORSET_06_VEC"
    COLORSET_07_VEC = "COLORSET_07_VEC"
    COLORSET_08_VEC = "COLORSET_08_VEC"
    COLORSET_09_VEC = "COLORSET_09_VEC"
    COLORSET_10_VEC = "COLORSET_10_VEC"
    COLORSET_11_VEC = "COLORSET_11_VEC"
    COLORSET_12_VEC = "COLORSET_12_VEC"
    COLORSET_13_VEC = "COLORSET_13_VEC"
    COLORSET_14_VEC = "COLORSET_14_VEC"
    COLORSET_15_VEC = "COLORSET_15_VEC"
    COLORSET_16_VEC = "COLORSET_16_VEC"
    COLORSET_17_VEC = "COLORSET_17_VEC"
    COLORSET_18_VEC = "COLORSET_18_VEC"
    COLORSET_19_VEC = "COLORSET_19_VEC"
    COLORSET_20_VEC = "COLORSET_20_VEC"
    COLOR_BLUE = "COLOR_BLUE"
    COLOR_GREEN = "COLOR_GREEN"
    COLOR_RED = "COLOR_RED"
    COMMUNITY = "COMMUNITY"
    CONE = "CONE"
    CONSOLE = "CONSOLE"
    CONSTRAINT = "CONSTRAINT"
    CONSTRAINT_BONE = "CONSTRAINT_BONE"
    CON_ACTION = "CON_ACTION"
    CON_ARMATURE = "CON_ARMATURE"
    CON_CAMERASOLVER = "CON_CAMERASOLVER"
    CON_CHILDOF = "CON_CHILDOF"
    CON_CLAMPTO = "CON_CLAMPTO"
    CON_DISTLIMIT = "CON_DISTLIMIT"
    CON_FLOOR = "CON_FLOOR"
    CON_FOLLOWPATH = "CON_FOLLOWPATH"
    CON_FOLLOWTRACK = "CON_FOLLOWTRACK"
    CON_KINEMATIC = "CON_KINEMATIC"
    CON_LOCKTRACK = "CON_LOCKTRACK"
    CON_LOCLIKE = "CON_LOCLIKE"
    CON_LOCLIMIT = "CON_LOCLIMIT"
    CON_OBJECTSOLVER = "CON_OBJECTSOLVER"
    CON_PIVOT = "CON_PIVOT"
    CON_ROTLIKE = "CON_ROTLIKE"
    CON_ROTLIMIT = "CON_ROTLIMIT"
    CON_SAMEVOL = "CON_SAMEVOL"
    CON_SHRINKWRAP = "CON_SHRINKWRAP"
    CON_SIZELIKE = "CON_SIZELIKE"
    CON_SIZELIMIT = "CON_SIZELIMIT"
    CON_SPLINEIK = "CON_SPLINEIK"
    CON_STRETCHTO = "CON_STRETCHTO"
    CON_TRACKTO = "CON_TRACKTO"
    CON_TRANSFORM = "CON_TRANSFORM"
    CON_TRANSFORM_CACHE = "CON_TRANSFORM_CACHE"
    CON_TRANSLIKE = "CON_TRANSLIKE"
    COPYDOWN = "COPYDOWN"
    COPY_ID = "COPY_ID"
    CUBE = "CUBE"
    CURSOR = "CURSOR"
    CURVE_BEZCIRCLE = "CURVE_BEZCIRCLE"
    CURVE_BEZCURVE = "CURVE_BEZCURVE"
    CURVE_DATA = "CURVE_DATA"
    CURVE_NCIRCLE = "CURVE_NCIRCLE"
    CURVE_NCURVE = "CURVE_NCURVE"
    CURVE_PATH = "CURVE_PATH"
    DECORATE = "DECORATE"
    DECORATE_ANIMATE = "DECORATE_ANIMATE"
    DECORATE_DRIVER = "DECORATE_DRIVER"
    DECORATE_KEYFRAME = "DECORATE_KEYFRAME"
    DECORATE_LIBRARY_OVERRIDE = "DECORATE_LIBRARY_OVERRIDE"
    DECORATE_LINKED = "DECORATE_LINKED"
    DECORATE_LOCKED = "DECORATE_LOCKED"
    DECORATE_OVERRIDE = "DECORATE_OVERRIDE"
    DECORATE_UNLOCKED = "DECORATE_UNLOCKED"
    DESKTOP = "DESKTOP"
    DISC = "DISC"
    DISCLOSURE_TRI_DOWN = "DISCLOSURE_TRI_DOWN"
    DISCLOSURE_TRI_RIGHT = "DISCLOSURE_TRI_RIGHT"
    DISK_DRIVE = "DISK_DRIVE"
    DOCUMENTS = "DOCUMENTS"
    DOT = "DOT"
    DOWNARROW_HLT = "DOWNARROW_HLT"
    DRIVER = "DRIVER"
    DRIVER_DISTANCE = "DRIVER_DISTANCE"
    DRIVER_ROTATIONAL_DIFFERENCE = "DRIVER_ROTATIONAL_DIFFERENCE"
    DRIVER_TRANSFORM = "DRIVER_TRANSFORM"
    DUPLICATE = "DUPLICATE"
    EDGESEL = "EDGESEL"
    EDITMODE_HLT = "EDITMODE_HLT"
    EMPTY_ARROWS = "EMPTY_ARROWS"
    EMPTY_AXIS = "EMPTY_AXIS"
    EMPTY_DATA = "EMPTY_DATA"
    EMPTY_SINGLE_ARROW = "EMPTY_SINGLE_ARROW"
    ERROR = "ERROR"
    EVENT_A = "EVENT_A"
    EVENT_ALT = "EVENT_ALT"
    EVENT_B = "EVENT_B"
    EVENT_C = "EVENT_C"
    EVENT_CTRL = "EVENT_CTRL"
    EVENT_D = "EVENT_D"
    EVENT_E = "EVENT_E"
    EVENT_ESC = "EVENT_ESC"
    EVENT_F = "EVENT_F"
    EVENT_F1 = "EVENT_F1"
    EVENT_F10 = "EVENT_F10"
    EVENT_F11 = "EVENT_F11"
    EVENT_F12 = "EVENT_F12"
    EVENT_F2 = "EVENT_F2"
    EVENT_F3 = "EVENT_F3"
    EVENT_F4 = "EVENT_F4"
    EVENT_F5 = "EVENT_F5"
    EVENT_F6 = "EVENT_F6"
    EVENT_F7 = "EVENT_F7"
    EVENT_F8 = "EVENT_F8"
    EVENT_F9 = "EVENT_F9"
    EVENT_G = "EVENT_G"
    EVENT_H = "EVENT_H"
    EVENT_I = "EVENT_I"
    EVENT_J = "EVENT_J"
    EVENT_K = "EVENT_K"
    EVENT_L = "EVENT_L"
    EVENT_M = "EVENT_M"
    EVENT_N = "EVENT_N"
    EVENT_O = "EVENT_O"
    EVENT_OS = "EVENT_OS"
    EVENT_P = "EVENT_P"
    EVENT_PAGEDOWN = "EVENT_PAGEDOWN"
    EVENT_PAGEUP = "EVENT_PAGEUP"
    EVENT_Q = "EVENT_Q"
    EVENT_R = "EVENT_R"
    EVENT_RETURN = "EVENT_RETURN"
    EVENT_S = "EVENT_S"
    EVENT_SHIFT = "EVENT_SHIFT"
    EVENT_SPACEKEY = "EVENT_SPACEKEY"
    EVENT_T = "EVENT_T"
    EVENT_TAB = "EVENT_TAB"
    EVENT_U = "EVENT_U"
    EVENT_V = "EVENT_V"
    EVENT_W = "EVENT_W"
    EVENT_X = "EVENT_X"
    EVENT_Y = "EVENT_Y"
    EVENT_Z = "EVENT_Z"
    EXPERIMENTAL = "EXPERIMENTAL"
    EXPORT = "EXPORT"
    EXTERNAL_DRIVE = "EXTERNAL_DRIVE"
    EYEDROPPER = "EYEDROPPER"
    FACESEL = "FACESEL"
    FACE_MAPS = "FACE_MAPS"
    FAKE_USER_OFF = "FAKE_USER_OFF"
    FAKE_USER_ON = "FAKE_USER_ON"
    FCURVE = "FCURVE"
    FCURVE_SNAPSHOT = "FCURVE_SNAPSHOT"
    FF = "FF"
    FILE = "FILE"
    FILEBROWSER = "FILEBROWSER"
    FILE_3D = "FILE_3D"
    FILE_ARCHIVE = "FILE_ARCHIVE"
    FILE_BACKUP = "FILE_BACKUP"
    FILE_BLANK = "FILE_BLANK"
    FILE_BLEND = "FILE_BLEND"
    FILE_CACHE = "FILE_CACHE"
    FILE_FOLDER = "FILE_FOLDER"
    FILE_FONT = "FILE_FONT"
    FILE_HIDDEN = "FILE_HIDDEN"
    FILE_IMAGE = "FILE_IMAGE"
    FILE_MOVIE = "FILE_MOVIE"
    FILE_NEW = "FILE_NEW"
    FILE_PARENT = "FILE_PARENT"
    FILE_REFRESH = "FILE_REFRESH"
    FILE_SCRIPT = "FILE_SCRIPT"
    FILE_SOUND = "FILE_SOUND"
    FILE_TEXT = "FILE_TEXT"
    FILE_TICK = "FILE_TICK"
    FILE_VOLUME = "FILE_VOLUME"
    FILTER = "FILTER"
    FOLDER_REDIRECT = "FOLDER_REDIRECT"
    FONTPREVIEW = "FONTPREVIEW"
    FONT_DATA = "FONT_DATA"
    FORCE_BOID = "FORCE_BOID"
    FORCE_CHARGE = "FORCE_CHARGE"
    FORCE_CURVE = "FORCE_CURVE"
    FORCE_DRAG = "FORCE_DRAG"
    FORCE_FLUIDFLOW = "FORCE_FLUIDFLOW"
    FORCE_FORCE = "FORCE_FORCE"
    FORCE_HARMONIC = "FORCE_HARMONIC"
    FORCE_LENNARDJONES = "FORCE_LENNARDJONES"
    FORCE_MAGNETIC = "FORCE_MAGNETIC"
    FORCE_TEXTURE = "FORCE_TEXTURE"
    FORCE_TURBULENCE = "FORCE_TURBULENCE"
    FORCE_VORTEX = "FORCE_VORTEX"
    FORCE_WIND = "FORCE_WIND"
    FORWARD = "FORWARD"
    FRAME_NEXT = "FRAME_NEXT"
    FRAME_PREV = "FRAME_PREV"
    FREEZE = "FREEZE"
    FULLSCREEN_ENTER = "FULLSCREEN_ENTER"
    FULLSCREEN_EXIT = "FULLSCREEN_EXIT"
    FUND = "FUND"
    GHOST_DISABLED = "GHOST_DISABLED"
    GHOST_ENABLED = "GHOST_ENABLED"
    GIZMO = "GIZMO"
    GPBRUSH_AIRBRUSH = "GPBRUSH_AIRBRUSH"
    GPBRUSH_BLOCK = "GPBRUSH_BLOCK"
    GPBRUSH_CHISEL = "GPBRUSH_CHISEL"
    GPBRUSH_CLONE = "GPBRUSH_CLONE"
    GPBRUSH_ERASE_HARD = "GPBRUSH_ERASE_HARD"
    GPBRUSH_ERASE_SOFT = "GPBRUSH_ERASE_SOFT"
    GPBRUSH_ERASE_STROKE = "GPBRUSH_ERASE_STROKE"
    GPBRUSH_FILL = "GPBRUSH_FILL"
    GPBRUSH_GRAB = "GPBRUSH_GRAB"
    GPBRUSH_INK = "GPBRUSH_INK"
    GPBRUSH_INKNOISE = "GPBRUSH_INKNOISE"
    GPBRUSH_MARKER = "GPBRUSH_MARKER"
    GPBRUSH_PEN = "GPBRUSH_PEN"
    GPBRUSH_PENCIL = "GPBRUSH_PENCIL"
    GPBRUSH_PINCH = "GPBRUSH_PINCH"
    GPBRUSH_PUSH = "GPBRUSH_PUSH"
    GPBRUSH_RANDOMIZE = "GPBRUSH_RANDOMIZE"
    GPBRUSH_SMOOTH = "GPBRUSH_SMOOTH"
    GPBRUSH_STRENGTH = "GPBRUSH_STRENGTH"
    GPBRUSH_THICKNESS = "GPBRUSH_THICKNESS"
    GPBRUSH_TWIST = "GPBRUSH_TWIST"
    GPBRUSH_WEIGHT = "GPBRUSH_WEIGHT"
    GP_MULTIFRAME_EDITING = "GP_MULTIFRAME_EDITING"
    GP_ONLY_SELECTED = "GP_ONLY_SELECTED"
    GP_SELECT_BETWEEN_STROKES = "GP_SELECT_BETWEEN_STROKES"
    GP_SELECT_POINTS = "GP_SELECT_POINTS"
    GP_SELECT_STROKES = "GP_SELECT_STROKES"
    GRAPH = "GRAPH"
    GREASEPENCIL = "GREASEPENCIL"
    GRID = "GRID"
    GRIP = "GRIP"
    GROUP = "GROUP"
    GROUP_BONE = "GROUP_BONE"
    GROUP_UVS = "GROUP_UVS"
    GROUP_VCOL = "GROUP_VCOL"
    GROUP_VERTEX = "GROUP_VERTEX"
    HAIR = "HAIR"
    HAIR_DATA = "HAIR_DATA"
    HAND = "HAND"
    HANDLETYPE_ALIGNED_VEC = "HANDLETYPE_ALIGNED_VEC"
    HANDLETYPE_AUTO_CLAMP_VEC = "HANDLETYPE_AUTO_CLAMP_VEC"
    HANDLETYPE_AUTO_VEC = "HANDLETYPE_AUTO_VEC"
    HANDLETYPE_FREE_VEC = "HANDLETYPE_FREE_VEC"
    HANDLETYPE_VECTOR_VEC = "HANDLETYPE_VECTOR_VEC"
    HANDLE_ALIGNED = "HANDLE_ALIGNED"
    HANDLE_AUTO = "HANDLE_AUTO"
    HANDLE_AUTOCLAMPED = "HANDLE_AUTOCLAMPED"
    HANDLE_FREE = "HANDLE_FREE"
    HANDLE_VECTOR = "HANDLE_VECTOR"
    HEART = "HEART"
    HELP = "HELP"
    HIDE_OFF = "HIDE_OFF"
    HIDE_ON = "HIDE_ON"
    HOLDOUT_OFF = "HOLDOUT_OFF"
    HOLDOUT_ON = "HOLDOUT_ON"
    HOME = "HOME"
    HOOK = "HOOK"
    IMAGE = "IMAGE"
    IMAGE_ALPHA = "IMAGE_ALPHA"
    IMAGE_BACKGROUND = "IMAGE_BACKGROUND"
    IMAGE_DATA = "IMAGE_DATA"
    IMAGE_PLANE = "IMAGE_PLANE"
    IMAGE_REFERENCE = "IMAGE_REFERENCE"
    IMAGE_RGB = "IMAGE_RGB"
    IMAGE_RGB_ALPHA = "IMAGE_RGB_ALPHA"
    IMAGE_ZDEPTH = "IMAGE_ZDEPTH"
    IMGDISPLAY = "IMGDISPLAY"
    IMPORT = "IMPORT"
    INDIRECT_ONLY_OFF = "INDIRECT_ONLY_OFF"
    INDIRECT_ONLY_ON = "INDIRECT_ONLY_ON"
    INFO = "INFO"
    INVERSESQUARECURVE = "INVERSESQUARECURVE"
    IPO_BACK = "IPO_BACK"
    IPO_BEZIER = "IPO_BEZIER"
    IPO_BOUNCE = "IPO_BOUNCE"
    IPO_CIRC = "IPO_CIRC"
    IPO_CONSTANT = "IPO_CONSTANT"
    IPO_CUBIC = "IPO_CUBIC"
    IPO_EASE_IN = "IPO_EASE_IN"
    IPO_EASE_IN_OUT = "IPO_EASE_IN_OUT"
    IPO_EASE_OUT = "IPO_EASE_OUT"
    IPO_ELASTIC = "IPO_ELASTIC"
    IPO_EXPO = "IPO_EXPO"
    IPO_LINEAR = "IPO_LINEAR"
    IPO_QUAD = "IPO_QUAD"
    IPO_QUART = "IPO_QUART"
    IPO_QUINT = "IPO_QUINT"
    IPO_SINE = "IPO_SINE"
    ITALIC = "ITALIC"
    KEYFRAME = "KEYFRAME"
    KEYFRAME_HLT = "KEYFRAME_HLT"
    KEYINGSET = "KEYINGSET"
    KEYTYPE_BREAKDOWN_VEC = "KEYTYPE_BREAKDOWN_VEC"
    KEYTYPE_EXTREME_VEC = "KEYTYPE_EXTREME_VEC"
    KEYTYPE_JITTER_VEC = "KEYTYPE_JITTER_VEC"
    KEYTYPE_KEYFRAME_VEC = "KEYTYPE_KEYFRAME_VEC"
    KEYTYPE_MOVING_HOLD_VEC = "KEYTYPE_MOVING_HOLD_VEC"
    KEY_DEHLT = "KEY_DEHLT"
    KEY_HLT = "KEY_HLT"
    LATTICE_DATA = "LATTICE_DATA"
    LAYER_ACTIVE = "LAYER_ACTIVE"
    LAYER_USED = "LAYER_USED"
    LIBRARY_DATA_BROKEN = "LIBRARY_DATA_BROKEN"
    LIBRARY_DATA_DIRECT = "LIBRARY_DATA_DIRECT"
    LIBRARY_DATA_INDIRECT = "LIBRARY_DATA_INDIRECT"
    LIBRARY_DATA_OVERRIDE = "LIBRARY_DATA_OVERRIDE"
    LIGHT = "LIGHT"
    LIGHTPROBE_CUBEMAP = "LIGHTPROBE_CUBEMAP"
    LIGHTPROBE_GRID = "LIGHTPROBE_GRID"
    LIGHTPROBE_PLANAR = "LIGHTPROBE_PLANAR"
    LIGHT_AREA = "LIGHT_AREA"
    LIGHT_DATA = "LIGHT_DATA"
    LIGHT_HEMI = "LIGHT_HEMI"
    LIGHT_POINT = "LIGHT_POINT"
    LIGHT_SPOT = "LIGHT_SPOT"
    LIGHT_SUN = "LIGHT_SUN"
    LINCURVE = "LINCURVE"
    LINENUMBERS_OFF = "LINENUMBERS_OFF"
    LINENUMBERS_ON = "LINENUMBERS_ON"
    LINE_DATA = "LINE_DATA"
    LINKED = "LINKED"
    LINK_BLEND = "LINK_BLEND"
    LOCKED = "LOCKED"
    LOCKVIEW_OFF = "LOCKVIEW_OFF"
    LOCKVIEW_ON = "LOCKVIEW_ON"
    LONGDISPLAY = "LONGDISPLAY"
    LOOP_BACK = "LOOP_BACK"
    LOOP_FORWARDS = "LOOP_FORWARDS"
    MARKER = "MARKER"
    MARKER_HLT = "MARKER_HLT"
    MATCLOTH = "MATCLOTH"
    MATCUBE = "MATCUBE"
    MATERIAL = "MATERIAL"
    MATERIAL_DATA = "MATERIAL_DATA"
    MATFLUID = "MATFLUID"
    MATPLANE = "MATPLANE"
    MATSHADERBALL = "MATSHADERBALL"
    MATSPHERE = "MATSPHERE"
    MAT_SPHERE_SKY = "MAT_SPHERE_SKY"
    MEMORY = "MEMORY"
    MENU_PANEL = "MENU_PANEL"
    MESH_CAPSULE = "MESH_CAPSULE"
    MESH_CIRCLE = "MESH_CIRCLE"
    MESH_CONE = "MESH_CONE"
    MESH_CUBE = "MESH_CUBE"
    MESH_CYLINDER = "MESH_CYLINDER"
    MESH_DATA = "MESH_DATA"
    MESH_GRID = "MESH_GRID"
    MESH_ICOSPHERE = "MESH_ICOSPHERE"
    MESH_MONKEY = "MESH_MONKEY"
    MESH_PLANE = "MESH_PLANE"
    MESH_TORUS = "MESH_TORUS"
    MESH_UVSPHERE = "MESH_UVSPHERE"
    META_BALL = "META_BALL"
    META_CAPSULE = "META_CAPSULE"
    META_CUBE = "META_CUBE"
    META_DATA = "META_DATA"
    META_ELLIPSOID = "META_ELLIPSOID"
    META_PLANE = "META_PLANE"
    MODIFIER = "MODIFIER"
    MODIFIER_DATA = "MODIFIER_DATA"
    MODIFIER_OFF = "MODIFIER_OFF"
    MODIFIER_ON = "MODIFIER_ON"
    MOD_ARMATURE = "MOD_ARMATURE"
    MOD_ARRAY = "MOD_ARRAY"
    MOD_BEVEL = "MOD_BEVEL"
    MOD_BOOLEAN = "MOD_BOOLEAN"
    MOD_BUILD = "MOD_BUILD"
    MOD_CAST = "MOD_CAST"
    MOD_CLOTH = "MOD_CLOTH"
    MOD_CURVE = "MOD_CURVE"
    MOD_DATA_TRANSFER = "MOD_DATA_TRANSFER"
    MOD_DECIM = "MOD_DECIM"
    MOD_DISPLACE = "MOD_DISPLACE"
    MOD_DYNAMICPAINT = "MOD_DYNAMICPAINT"
    MOD_EDGESPLIT = "MOD_EDGESPLIT"
    MOD_EXPLODE = "MOD_EXPLODE"
    MOD_FLUID = "MOD_FLUID"
    MOD_FLUIDSIM = "MOD_FLUIDSIM"
    MOD_HUE_SATURATION = "MOD_HUE_SATURATION"
    MOD_INSTANCE = "MOD_INSTANCE"
    MOD_LATTICE = "MOD_LATTICE"
    MOD_MASK = "MOD_MASK"
    MOD_MESHDEFORM = "MOD_MESHDEFORM"
    MOD_MIRROR = "MOD_MIRROR"
    MOD_MULTIRES = "MOD_MULTIRES"
    MOD_NOISE = "MOD_NOISE"
    MOD_NORMALEDIT = "MOD_NORMALEDIT"
    MOD_OCEAN = "MOD_OCEAN"
    MOD_OFFSET = "MOD_OFFSET"
    MOD_OPACITY = "MOD_OPACITY"
    MOD_PARTICLES = "MOD_PARTICLES"
    MOD_PARTICLE_INSTANCE = "MOD_PARTICLE_INSTANCE"
    MOD_PHYSICS = "MOD_PHYSICS"
    MOD_REMESH = "MOD_REMESH"
    MOD_SCREW = "MOD_SCREW"
    MOD_SHRINKWRAP = "MOD_SHRINKWRAP"
    MOD_SIMPLEDEFORM = "MOD_SIMPLEDEFORM"
    MOD_SIMPLIFY = "MOD_SIMPLIFY"
    MOD_SKIN = "MOD_SKIN"
    MOD_SMOOTH = "MOD_SMOOTH"
    MOD_SOFT = "MOD_SOFT"
    MOD_SOLIDIFY = "MOD_SOLIDIFY"
    MOD_SUBSURF = "MOD_SUBSURF"
    MOD_THICKNESS = "MOD_THICKNESS"
    MOD_TIME = "MOD_TIME"
    MOD_TINT = "MOD_TINT"
    MOD_TRIANGULATE = "MOD_TRIANGULATE"
    MOD_UVPROJECT = "MOD_UVPROJECT"
    MOD_VERTEX_WEIGHT = "MOD_VERTEX_WEIGHT"
    MOD_WARP = "MOD_WARP"
    MOD_WAVE = "MOD_WAVE"
    MOD_WIREFRAME = "MOD_WIREFRAME"
    MONKEY = "MONKEY"
    MOUSE_LMB = "MOUSE_LMB"
    MOUSE_LMB_DRAG = "MOUSE_LMB_DRAG"
    MOUSE_MMB = "MOUSE_MMB"
    MOUSE_MMB_DRAG = "MOUSE_MMB_DRAG"
    MOUSE_MOVE = "MOUSE_MOVE"
    MOUSE_RMB = "MOUSE_RMB"
    MOUSE_RMB_DRAG = "MOUSE_RMB_DRAG"
    MUTE_IPO_OFF = "MUTE_IPO_OFF"
    MUTE_IPO_ON = "MUTE_IPO_ON"
    NETWORK_DRIVE = "NETWORK_DRIVE"
    NEWFOLDER = "NEWFOLDER"
    NEXT_KEYFRAME = "NEXT_KEYFRAME"
    NLA = "NLA"
    NLA_PUSHDOWN = "NLA_PUSHDOWN"
    NOCURVE = "NOCURVE"
    NODE = "NODE"
    NODETREE = "NODETREE"
    NODE_COMPOSITING = "NODE_COMPOSITING"
    NODE_CORNER = "NODE_CORNER"
    NODE_INSERT_OFF = "NODE_INSERT_OFF"
    NODE_INSERT_ON = "NODE_INSERT_ON"
    NODE_MATERIAL = "NODE_MATERIAL"
    NODE_SEL = "NODE_SEL"
    NODE_SIDE = "NODE_SIDE"
    NODE_TEXTURE = "NODE_TEXTURE"
    NODE_TOP = "NODE_TOP"
    NONE = "NONE"
    NORMALIZE_FCURVES = "NORMALIZE_FCURVES"
    NORMALS_FACE = "NORMALS_FACE"
    NORMALS_VERTEX = "NORMALS_VERTEX"
    NORMALS_VERTEX_FACE = "NORMALS_VERTEX_FACE"
    OBJECT_DATA = "OBJECT_DATA"
    OBJECT_DATAMODE = "OBJECT_DATAMODE"
    OBJECT_HIDDEN = "OBJECT_HIDDEN"
    OBJECT_ORIGIN = "OBJECT_ORIGIN"
    ONIONSKIN_OFF = "ONIONSKIN_OFF"
    ONIONSKIN_ON = "ONIONSKIN_ON"
    OPTIONS = "OPTIONS"
    ORIENTATION_CURSOR = "ORIENTATION_CURSOR"
    ORIENTATION_GIMBAL = "ORIENTATION_GIMBAL"
    ORIENTATION_GLOBAL = "ORIENTATION_GLOBAL"
    ORIENTATION_LOCAL = "ORIENTATION_LOCAL"
    ORIENTATION_NORMAL = "ORIENTATION_NORMAL"
    ORIENTATION_VIEW = "ORIENTATION_VIEW"
    ORPHAN_DATA = "ORPHAN_DATA"
    OUTLINER = "OUTLINER"
    OUTLINER_COLLECTION = "OUTLINER_COLLECTION"
    OUTLINER_DATA_ARMATURE = "OUTLINER_DATA_ARMATURE"
    OUTLINER_DATA_CAMERA = "OUTLINER_DATA_CAMERA"
    OUTLINER_DATA_CURVE = "OUTLINER_DATA_CURVE"
    OUTLINER_DATA_EMPTY = "OUTLINER_DATA_EMPTY"
    OUTLINER_DATA_FONT = "OUTLINER_DATA_FONT"
    OUTLINER_DATA_GP_LAYER = "OUTLINER_DATA_GP_LAYER"
    OUTLINER_DATA_GREASEPENCIL = "OUTLINER_DATA_GREASEPENCIL"
    OUTLINER_DATA_HAIR = "OUTLINER_DATA_HAIR"
    OUTLINER_DATA_LATTICE = "OUTLINER_DATA_LATTICE"
    OUTLINER_DATA_LIGHT = "OUTLINER_DATA_LIGHT"
    OUTLINER_DATA_LIGHTPROBE = "OUTLINER_DATA_LIGHTPROBE"
    OUTLINER_DATA_MESH = "OUTLINER_DATA_MESH"
    OUTLINER_DATA_META = "OUTLINER_DATA_META"
    OUTLINER_DATA_POINTCLOUD = "OUTLINER_DATA_POINTCLOUD"
    OUTLINER_DATA_SPEAKER = "OUTLINER_DATA_SPEAKER"
    OUTLINER_DATA_SURFACE = "OUTLINER_DATA_SURFACE"
    OUTLINER_DATA_VOLUME = "OUTLINER_DATA_VOLUME"
    OUTLINER_OB_ARMATURE = "OUTLINER_OB_ARMATURE"
    OUTLINER_OB_CAMERA = "OUTLINER_OB_CAMERA"
    OUTLINER_OB_CURVE = "OUTLINER_OB_CURVE"
    OUTLINER_OB_EMPTY = "OUTLINER_OB_EMPTY"
    OUTLINER_OB_FONT = "OUTLINER_OB_FONT"
    OUTLINER_OB_FORCE_FIELD = "OUTLINER_OB_FORCE_FIELD"
    OUTLINER_OB_GREASEPENCIL = "OUTLINER_OB_GREASEPENCIL"
    OUTLINER_OB_GROUP_INSTANCE = "OUTLINER_OB_GROUP_INSTANCE"
    OUTLINER_OB_HAIR = "OUTLINER_OB_HAIR"
    OUTLINER_OB_IMAGE = "OUTLINER_OB_IMAGE"
    OUTLINER_OB_LATTICE = "OUTLINER_OB_LATTICE"
    OUTLINER_OB_LIGHT = "OUTLINER_OB_LIGHT"
    OUTLINER_OB_LIGHTPROBE = "OUTLINER_OB_LIGHTPROBE"
    OUTLINER_OB_MESH = "OUTLINER_OB_MESH"
    OUTLINER_OB_META = "OUTLINER_OB_META"
    OUTLINER_OB_POINTCLOUD = "OUTLINER_OB_POINTCLOUD"
    OUTLINER_OB_SPEAKER = "OUTLINER_OB_SPEAKER"
    OUTLINER_OB_SURFACE = "OUTLINER_OB_SURFACE"
    OUTLINER_OB_VOLUME = "OUTLINER_OB_VOLUME"
    OUTPUT = "OUTPUT"
    OVERLAY = "OVERLAY"
    PACKAGE = "PACKAGE"
    PANEL_CLOSE = "PANEL_CLOSE"
    PARTICLEMODE = "PARTICLEMODE"
    PARTICLES = "PARTICLES"
    PARTICLE_DATA = "PARTICLE_DATA"
    PARTICLE_PATH = "PARTICLE_PATH"
    PARTICLE_POINT = "PARTICLE_POINT"
    PARTICLE_TIP = "PARTICLE_TIP"
    PASTEDOWN = "PASTEDOWN"
    PASTEFLIPDOWN = "PASTEFLIPDOWN"
    PASTEFLIPUP = "PASTEFLIPUP"
    PAUSE = "PAUSE"
    PHYSICS = "PHYSICS"
    PINNED = "PINNED"
    PIVOT_ACTIVE = "PIVOT_ACTIVE"
    PIVOT_BOUNDBOX = "PIVOT_BOUNDBOX"
    PIVOT_CURSOR = "PIVOT_CURSOR"
    PIVOT_INDIVIDUAL = "PIVOT_INDIVIDUAL"
    PIVOT_MEDIAN = "PIVOT_MEDIAN"
    PLAY = "PLAY"
    PLAY_REVERSE = "PLAY_REVERSE"
    PLAY_SOUND = "PLAY_SOUND"
    PLUGIN = "PLUGIN"
    PLUS = "PLUS"
    PMARKER = "PMARKER"
    PMARKER_ACT = "PMARKER_ACT"
    PMARKER_SEL = "PMARKER_SEL"
    POINTCLOUD_DATA = "POINTCLOUD_DATA"
    POSE_HLT = "POSE_HLT"
    PREFERENCES = "PREFERENCES"
    PRESET = "PRESET"
    PRESET_NEW = "PRESET_NEW"
    PREVIEW_RANGE = "PREVIEW_RANGE"
    PREV_KEYFRAME = "PREV_KEYFRAME"
    PROPERTIES = "PROPERTIES"
    PROP_CON = "PROP_CON"
    PROP_OFF = "PROP_OFF"
    PROP_ON = "PROP_ON"
    PROP_PROJECTED = "PROP_PROJECTED"
    QUESTION = "QUESTION"
    QUIT = "QUIT"
    RADIOBUT_OFF = "RADIOBUT_OFF"
    RADIOBUT_ON = "RADIOBUT_ON"
    REC = "REC"
    RECOVER_LAST = "RECOVER_LAST"
    REMOVE = "REMOVE"
    RENDERLAYERS = "RENDERLAYERS"
    RENDER_ANIMATION = "RENDER_ANIMATION"
    RENDER_RESULT = "RENDER_RESULT"
    RENDER_STILL = "RENDER_STILL"
    RESTRICT_COLOR_OFF = "RESTRICT_COLOR_OFF"
    RESTRICT_COLOR_ON = "RESTRICT_COLOR_ON"
    RESTRICT_INSTANCED_OFF = "RESTRICT_INSTANCED_OFF"
    RESTRICT_INSTANCED_ON = "RESTRICT_INSTANCED_ON"
    RESTRICT_RENDER_OFF = "RESTRICT_RENDER_OFF"
    RESTRICT_RENDER_ON = "RESTRICT_RENDER_ON"
    RESTRICT_SELECT_OFF = "RESTRICT_SELECT_OFF"
    RESTRICT_SELECT_ON = "RESTRICT_SELECT_ON"
    RESTRICT_VIEW_OFF = "RESTRICT_VIEW_OFF"
    RESTRICT_VIEW_ON = "RESTRICT_VIEW_ON"
    REW = "REW"
    RIGHTARROW = "RIGHTARROW"
    RIGHTARROW_THIN = "RIGHTARROW_THIN"
    RIGID_BODY = "RIGID_BODY"
    RIGID_BODY_CONSTRAINT = "RIGID_BODY_CONSTRAINT"
    RNA = "RNA"
    RNA_ADD = "RNA_ADD"
    RNDCURVE = "RNDCURVE"
    ROOTCURVE = "ROOTCURVE"
    SCENE = "SCENE"
    SCENE_DATA = "SCENE_DATA"
    SCREEN_BACK = "SCREEN_BACK"
    SCRIPT = "SCRIPT"
    SCRIPTPLUGINS = "SCRIPTPLUGINS"
    SCULPTMODE_HLT = "SCULPTMODE_HLT"
    SELECT_DIFFERENCE = "SELECT_DIFFERENCE"
    SELECT_EXTEND = "SELECT_EXTEND"
    SELECT_INTERSECT = "SELECT_INTERSECT"
    SELECT_SET = "SELECT_SET"
    SELECT_SUBTRACT = "SELECT_SUBTRACT"
    SEQUENCE = "SEQUENCE"
    SEQ_CHROMA_SCOPE = "SEQ_CHROMA_SCOPE"
    SEQ_HISTOGRAM = "SEQ_HISTOGRAM"
    SEQ_LUMA_WAVEFORM = "SEQ_LUMA_WAVEFORM"
    SEQ_PREVIEW = "SEQ_PREVIEW"
    SEQ_SEQUENCER = "SEQ_SEQUENCER"
    SEQ_SPLITVIEW = "SEQ_SPLITVIEW"
    SEQ_STRIP_DUPLICATE = "SEQ_STRIP_DUPLICATE"
    SEQ_STRIP_META = "SEQ_STRIP_META"
    SETTINGS = "SETTINGS"
    SHADERFX = "SHADERFX"
    SHADING_BBOX = "SHADING_BBOX"
    SHADING_RENDERED = "SHADING_RENDERED"
    SHADING_SOLID = "SHADING_SOLID"
    SHADING_TEXTURE = "SHADING_TEXTURE"
    SHADING_WIRE = "SHADING_WIRE"
    SHAPEKEY_DATA = "SHAPEKEY_DATA"
    SHARPCURVE = "SHARPCURVE"
    SHORTDISPLAY = "SHORTDISPLAY"
    SMALL_CAPS = "SMALL_CAPS"
    SMALL_TRI_RIGHT_VEC = "SMALL_TRI_RIGHT_VEC"
    SMOOTHCURVE = "SMOOTHCURVE"
    SNAP_EDGE = "SNAP_EDGE"
    SNAP_FACE = "SNAP_FACE"
    SNAP_FACE_CENTER = "SNAP_FACE_CENTER"
    SNAP_GRID = "SNAP_GRID"
    SNAP_INCREMENT = "SNAP_INCREMENT"
    SNAP_MIDPOINT = "SNAP_MIDPOINT"
    SNAP_NORMAL = "SNAP_NORMAL"
    SNAP_OFF = "SNAP_OFF"
    SNAP_ON = "SNAP_ON"
    SNAP_PEEL_OBJECT = "SNAP_PEEL_OBJECT"
    SNAP_PERPENDICULAR = "SNAP_PERPENDICULAR"
    SNAP_VERTEX = "SNAP_VERTEX"
    SNAP_VOLUME = "SNAP_VOLUME"
    SOLO_OFF = "SOLO_OFF"
    SOLO_ON = "SOLO_ON"
    SORTALPHA = "SORTALPHA"
    SORTBYEXT = "SORTBYEXT"
    SORTSIZE = "SORTSIZE"
    SORTTIME = "SORTTIME"
    SORT_ASC = "SORT_ASC"
    SORT_DESC = "SORT_DESC"
    SOUND = "SOUND"
    SPEAKER = "SPEAKER"
    SPHERE = "SPHERE"
    SPHERECURVE = "SPHERECURVE"
    STATUSBAR = "STATUSBAR"
    STICKY_UVS_DISABLE = "STICKY_UVS_DISABLE"
    STICKY_UVS_LOC = "STICKY_UVS_LOC"
    STICKY_UVS_VERT = "STICKY_UVS_VERT"
    STRANDS = "STRANDS"
    STROKE = "STROKE"
    STYLUS_PRESSURE = "STYLUS_PRESSURE"
    SURFACE_DATA = "SURFACE_DATA"
    SURFACE_NCIRCLE = "SURFACE_NCIRCLE"
    SURFACE_NCURVE = "SURFACE_NCURVE"
    SURFACE_NCYLINDER = "SURFACE_NCYLINDER"
    SURFACE_NSPHERE = "SURFACE_NSPHERE"
    SURFACE_NSURFACE = "SURFACE_NSURFACE"
    SURFACE_NTORUS = "SURFACE_NTORUS"
    SYNTAX_OFF = "SYNTAX_OFF"
    SYNTAX_ON = "SYNTAX_ON"
    SYSTEM = "SYSTEM"
    TEMP = "TEMP"
    TEXT = "TEXT"
    TEXTURE = "TEXTURE"
    TEXTURE_DATA = "TEXTURE_DATA"
    THREE_DOTS = "THREE_DOTS"
    TIME = "TIME"
    TOOL_SETTINGS = "TOOL_SETTINGS"
    TOPBAR = "TOPBAR"
    TPAINT_HLT = "TPAINT_HLT"
    TRACKER = "TRACKER"
    TRACKER_DATA = "TRACKER_DATA"
    TRACKING = "TRACKING"
    TRACKING_BACKWARDS = "TRACKING_BACKWARDS"
    TRACKING_BACKWARDS_SINGLE = "TRACKING_BACKWARDS_SINGLE"
    TRACKING_CLEAR_BACKWARDS = "TRACKING_CLEAR_BACKWARDS"
    TRACKING_CLEAR_FORWARDS = "TRACKING_CLEAR_FORWARDS"
    TRACKING_FORWARDS = "TRACKING_FORWARDS"
    TRACKING_FORWARDS_SINGLE = "TRACKING_FORWARDS_SINGLE"
    TRACKING_REFINE_BACKWARDS = "TRACKING_REFINE_BACKWARDS"
    TRACKING_REFINE_FORWARDS = "TRACKING_REFINE_FORWARDS"
    TRANSFORM_ORIGINS = "TRANSFORM_ORIGINS"
    TRASH = "TRASH"
    TRIA_DOWN = "TRIA_DOWN"
    TRIA_DOWN_BAR = "TRIA_DOWN_BAR"
    TRIA_LEFT = "TRIA_LEFT"
    TRIA_LEFT_BAR = "TRIA_LEFT_BAR"
    TRIA_RIGHT = "TRIA_RIGHT"
    TRIA_RIGHT_BAR = "TRIA_RIGHT_BAR"
    TRIA_UP = "TRIA_UP"
    TRIA_UP_BAR = "TRIA_UP_BAR"
    UGLYPACKAGE = "UGLYPACKAGE"
    UNDERLINE = "UNDERLINE"
    UNLINKED = "UNLINKED"
    UNLOCKED = "UNLOCKED"
    UNPINNED = "UNPINNED"
    URL = "URL"
    USER = "USER"
    UV = "UV"
    UV_DATA = "UV_DATA"
    UV_EDGESEL = "UV_EDGESEL"
    UV_FACESEL = "UV_FACESEL"
    UV_ISLANDSEL = "UV_ISLANDSEL"
    UV_SYNC_SELECT = "UV_SYNC_SELECT"
    UV_VERTEXSEL = "UV_VERTEXSEL"
    VERTEXSEL = "VERTEXSEL"
    VIEW3D = "VIEW3D"
    VIEWZOOM = "VIEWZOOM"
    VIEW_CAMERA = "VIEW_CAMERA"
    VIEW_ORTHO = "VIEW_ORTHO"
    VIEW_PAN = "VIEW_PAN"
    VIEW_PERSPECTIVE = "VIEW_PERSPECTIVE"
    VIEW_ZOOM = "VIEW_ZOOM"
    VIS_SEL_00 = "VIS_SEL_00"
    VIS_SEL_01 = "VIS_SEL_01"
    VIS_SEL_10 = "VIS_SEL_10"
    VIS_SEL_11 = "VIS_SEL_11"
    VOLUME_DATA = "VOLUME_DATA"
    VPAINT_HLT = "VPAINT_HLT"
    WINDOW = "WINDOW"
    WORDWRAP_OFF = "WORDWRAP_OFF"
    WORDWRAP_ON = "WORDWRAP_ON"
    WORKSPACE = "WORKSPACE"
    WORLD = "WORLD"
    WORLD_DATA = "WORLD_DATA"
    WPAINT_HLT = "WPAINT_HLT"
    X = "X"
    XRAY = "XRAY"
    ZOOM_ALL = "ZOOM_ALL"
    ZOOM_IN = "ZOOM_IN"
    ZOOM_OUT = "ZOOM_OUT"
    ZOOM_PREVIOUS = "ZOOM_PREVIOUS"
    ZOOM_SELECTED = "ZOOM_SELECTED"

    ALL_ = [
        ACTION,
        ACTION_TWEAK,
        ADD,
        ALIASED,
        ALIGN_BOTTOM,
        ALIGN_CENTER,
        ALIGN_FLUSH,
        ALIGN_JUSTIFY,
        ALIGN_LEFT,
        ALIGN_MIDDLE,
        ALIGN_RIGHT,
        ALIGN_TOP,
        ANCHOR_BOTTOM,
        ANCHOR_CENTER,
        ANCHOR_LEFT,
        ANCHOR_RIGHT,
        ANCHOR_TOP,
        ANIM,
        ANIM_DATA,
        ANTIALIASED,
        APPEND_BLEND,
        ARMATURE_DATA,
        ARROW_LEFTRIGHT,
        ASSET_MANAGER,
        AUTO,
        AUTOMERGE_OFF,
        AUTOMERGE_ON,
        AXIS_FRONT,
        AXIS_SIDE,
        AXIS_TOP,
        BACK,
        BLANK1,
        BLENDER,
        BOIDS,
        BOLD,
        BONE_DATA,
        BOOKMARKS,
        BORDERMOVE,
        BRUSHES_ALL,
        BRUSH_BLOB,
        BRUSH_BLUR,
        BRUSH_CLAY,
        BRUSH_CLAY_STRIPS,
        BRUSH_CLONE,
        BRUSH_CREASE,
        BRUSH_DATA,
        BRUSH_FILL,
        BRUSH_FLATTEN,
        BRUSH_GRAB,
        BRUSH_INFLATE,
        BRUSH_LAYER,
        BRUSH_MASK,
        BRUSH_MIX,
        BRUSH_NUDGE,
        BRUSH_PINCH,
        BRUSH_ROTATE,
        BRUSH_SCRAPE,
        BRUSH_SCULPT_DRAW,
        BRUSH_SMEAR,
        BRUSH_SMOOTH,
        BRUSH_SNAKE_HOOK,
        BRUSH_SOFTEN,
        BRUSH_TEXDRAW,
        BRUSH_TEXFILL,
        BRUSH_TEXMASK,
        BRUSH_THUMB,
        CAMERA_DATA,
        CAMERA_STEREO,
        CANCEL,
        CENTER_ONLY,
        CHECKBOX_DEHLT,
        CHECKBOX_HLT,
        CHECKMARK,
        CLIPUV_DEHLT,
        CLIPUV_HLT,
        COLLAPSEMENU,
        COLLECTION_COLOR_01,
        COLLECTION_COLOR_02,
        COLLECTION_COLOR_03,
        COLLECTION_COLOR_04,
        COLLECTION_COLOR_05,
        COLLECTION_COLOR_06,
        COLLECTION_COLOR_07,
        COLLECTION_COLOR_08,
        COLLECTION_NEW,
        COLOR,
        COLORSET_01_VEC,
        COLORSET_02_VEC,
        COLORSET_03_VEC,
        COLORSET_04_VEC,
        COLORSET_05_VEC,
        COLORSET_06_VEC,
        COLORSET_07_VEC,
        COLORSET_08_VEC,
        COLORSET_09_VEC,
        COLORSET_10_VEC,
        COLORSET_11_VEC,
        COLORSET_12_VEC,
        COLORSET_13_VEC,
        COLORSET_14_VEC,
        COLORSET_15_VEC,
        COLORSET_16_VEC,
        COLORSET_17_VEC,
        COLORSET_18_VEC,
        COLORSET_19_VEC,
        COLORSET_20_VEC,
        COLOR_BLUE,
        COLOR_GREEN,
        COLOR_RED,
        COMMUNITY,
        CONE,
        CONSOLE,
        CONSTRAINT,
        CONSTRAINT_BONE,
        CON_ACTION,
        CON_ARMATURE,
        CON_CAMERASOLVER,
        CON_CHILDOF,
        CON_CLAMPTO,
        CON_DISTLIMIT,
        CON_FLOOR,
        CON_FOLLOWPATH,
        CON_FOLLOWTRACK,
        CON_KINEMATIC,
        CON_LOCKTRACK,
        CON_LOCLIKE,
        CON_LOCLIMIT,
        CON_OBJECTSOLVER,
        CON_PIVOT,
        CON_ROTLIKE,
        CON_ROTLIMIT,
        CON_SAMEVOL,
        CON_SHRINKWRAP,
        CON_SIZELIKE,
        CON_SIZELIMIT,
        CON_SPLINEIK,
        CON_STRETCHTO,
        CON_TRACKTO,
        CON_TRANSFORM,
        CON_TRANSFORM_CACHE,
        CON_TRANSLIKE,
        COPYDOWN,
        COPY_ID,
        CUBE,
        CURSOR,
        CURVE_BEZCIRCLE,
        CURVE_BEZCURVE,
        CURVE_DATA,
        CURVE_NCIRCLE,
        CURVE_NCURVE,
        CURVE_PATH,
        DECORATE,
        DECORATE_ANIMATE,
        DECORATE_DRIVER,
        DECORATE_KEYFRAME,
        DECORATE_LIBRARY_OVERRIDE,
        DECORATE_LINKED,
        DECORATE_LOCKED,
        DECORATE_OVERRIDE,
        DECORATE_UNLOCKED,
        DESKTOP,
        DISC,
        DISCLOSURE_TRI_DOWN,
        DISCLOSURE_TRI_RIGHT,
        DISK_DRIVE,
        DOCUMENTS,
        DOT,
        DOWNARROW_HLT,
        DRIVER,
        DRIVER_DISTANCE,
        DRIVER_ROTATIONAL_DIFFERENCE,
        DRIVER_TRANSFORM,
        DUPLICATE,
        EDGESEL,
        EDITMODE_HLT,
        EMPTY_ARROWS,
        EMPTY_AXIS,
        EMPTY_DATA,
        EMPTY_SINGLE_ARROW,
        ERROR,
        EVENT_A,
        EVENT_ALT,
        EVENT_B,
        EVENT_C,
        EVENT_CTRL,
        EVENT_D,
        EVENT_E,
        EVENT_ESC,
        EVENT_F,
        EVENT_F1,
        EVENT_F10,
        EVENT_F11,
        EVENT_F12,
        EVENT_F2,
        EVENT_F3,
        EVENT_F4,
        EVENT_F5,
        EVENT_F6,
        EVENT_F7,
        EVENT_F8,
        EVENT_F9,
        EVENT_G,
        EVENT_H,
        EVENT_I,
        EVENT_J,
        EVENT_K,
        EVENT_L,
        EVENT_M,
        EVENT_N,
        EVENT_O,
        EVENT_OS,
        EVENT_P,
        EVENT_PAGEDOWN,
        EVENT_PAGEUP,
        EVENT_Q,
        EVENT_R,
        EVENT_RETURN,
        EVENT_S,
        EVENT_SHIFT,
        EVENT_SPACEKEY,
        EVENT_T,
        EVENT_TAB,
        EVENT_U,
        EVENT_V,
        EVENT_W,
        EVENT_X,
        EVENT_Y,
        EVENT_Z,
        EXPERIMENTAL,
        EXPORT,
        EXTERNAL_DRIVE,
        EYEDROPPER,
        FACESEL,
        FACE_MAPS,
        FAKE_USER_OFF,
        FAKE_USER_ON,
        FCURVE,
        FCURVE_SNAPSHOT,
        FF,
        FILE,
        FILEBROWSER,
        FILE_3D,
        FILE_ARCHIVE,
        FILE_BACKUP,
        FILE_BLANK,
        FILE_BLEND,
        FILE_CACHE,
        FILE_FOLDER,
        FILE_FONT,
        FILE_HIDDEN,
        FILE_IMAGE,
        FILE_MOVIE,
        FILE_NEW,
        FILE_PARENT,
        FILE_REFRESH,
        FILE_SCRIPT,
        FILE_SOUND,
        FILE_TEXT,
        FILE_TICK,
        FILE_VOLUME,
        FILTER,
        FOLDER_REDIRECT,
        FONTPREVIEW,
        FONT_DATA,
        FORCE_BOID,
        FORCE_CHARGE,
        FORCE_CURVE,
        FORCE_DRAG,
        FORCE_FLUIDFLOW,
        FORCE_FORCE,
        FORCE_HARMONIC,
        FORCE_LENNARDJONES,
        FORCE_MAGNETIC,
        FORCE_TEXTURE,
        FORCE_TURBULENCE,
        FORCE_VORTEX,
        FORCE_WIND,
        FORWARD,
        FRAME_NEXT,
        FRAME_PREV,
        FREEZE,
        FULLSCREEN_ENTER,
        FULLSCREEN_EXIT,
        FUND,
        GHOST_DISABLED,
        GHOST_ENABLED,
        GIZMO,
        GPBRUSH_AIRBRUSH,
        GPBRUSH_BLOCK,
        GPBRUSH_CHISEL,
        GPBRUSH_CLONE,
        GPBRUSH_ERASE_HARD,
        GPBRUSH_ERASE_SOFT,
        GPBRUSH_ERASE_STROKE,
        GPBRUSH_FILL,
        GPBRUSH_GRAB,
        GPBRUSH_INK,
        GPBRUSH_INKNOISE,
        GPBRUSH_MARKER,
        GPBRUSH_PEN,
        GPBRUSH_PENCIL,
        GPBRUSH_PINCH,
        GPBRUSH_PUSH,
        GPBRUSH_RANDOMIZE,
        GPBRUSH_SMOOTH,
        GPBRUSH_STRENGTH,
        GPBRUSH_THICKNESS,
        GPBRUSH_TWIST,
        GPBRUSH_WEIGHT,
        GP_MULTIFRAME_EDITING,
        GP_ONLY_SELECTED,
        GP_SELECT_BETWEEN_STROKES,
        GP_SELECT_POINTS,
        GP_SELECT_STROKES,
        GRAPH,
        GREASEPENCIL,
        GRID,
        GRIP,
        GROUP,
        GROUP_BONE,
        GROUP_UVS,
        GROUP_VCOL,
        GROUP_VERTEX,
        HAIR,
        HAIR_DATA,
        HAND,
        HANDLETYPE_ALIGNED_VEC,
        HANDLETYPE_AUTO_CLAMP_VEC,
        HANDLETYPE_AUTO_VEC,
        HANDLETYPE_FREE_VEC,
        HANDLETYPE_VECTOR_VEC,
        HANDLE_ALIGNED,
        HANDLE_AUTO,
        HANDLE_AUTOCLAMPED,
        HANDLE_FREE,
        HANDLE_VECTOR,
        HEART,
        HELP,
        HIDE_OFF,
        HIDE_ON,
        HOLDOUT_OFF,
        HOLDOUT_ON,
        HOME,
        HOOK,
        IMAGE,
        IMAGE_ALPHA,
        IMAGE_BACKGROUND,
        IMAGE_DATA,
        IMAGE_PLANE,
        IMAGE_REFERENCE,
        IMAGE_RGB,
        IMAGE_RGB_ALPHA,
        IMAGE_ZDEPTH,
        IMGDISPLAY,
        IMPORT,
        INDIRECT_ONLY_OFF,
        INDIRECT_ONLY_ON,
        INFO,
        INVERSESQUARECURVE,
        IPO_BACK,
        IPO_BEZIER,
        IPO_BOUNCE,
        IPO_CIRC,
        IPO_CONSTANT,
        IPO_CUBIC,
        IPO_EASE_IN,
        IPO_EASE_IN_OUT,
        IPO_EASE_OUT,
        IPO_ELASTIC,
        IPO_EXPO,
        IPO_LINEAR,
        IPO_QUAD,
        IPO_QUART,
        IPO_QUINT,
        IPO_SINE,
        ITALIC,
        KEYFRAME,
        KEYFRAME_HLT,
        KEYINGSET,
        KEYTYPE_BREAKDOWN_VEC,
        KEYTYPE_EXTREME_VEC,
        KEYTYPE_JITTER_VEC,
        KEYTYPE_KEYFRAME_VEC,
        KEYTYPE_MOVING_HOLD_VEC,
        KEY_DEHLT,
        KEY_HLT,
        LATTICE_DATA,
        LAYER_ACTIVE,
        LAYER_USED,
        LIBRARY_DATA_BROKEN,
        LIBRARY_DATA_DIRECT,
        LIBRARY_DATA_INDIRECT,
        LIBRARY_DATA_OVERRIDE,
        LIGHT,
        LIGHTPROBE_CUBEMAP,
        LIGHTPROBE_GRID,
        LIGHTPROBE_PLANAR,
        LIGHT_AREA,
        LIGHT_DATA,
        LIGHT_HEMI,
        LIGHT_POINT,
        LIGHT_SPOT,
        LIGHT_SUN,
        LINCURVE,
        LINENUMBERS_OFF,
        LINENUMBERS_ON,
        LINE_DATA,
        LINKED,
        LINK_BLEND,
        LOCKED,
        LOCKVIEW_OFF,
        LOCKVIEW_ON,
        LONGDISPLAY,
        LOOP_BACK,
        LOOP_FORWARDS,
        MARKER,
        MARKER_HLT,
        MATCLOTH,
        MATCUBE,
        MATERIAL,
        MATERIAL_DATA,
        MATFLUID,
        MATPLANE,
        MATSHADERBALL,
        MATSPHERE,
        MAT_SPHERE_SKY,
        MEMORY,
        MENU_PANEL,
        MESH_CAPSULE,
        MESH_CIRCLE,
        MESH_CONE,
        MESH_CUBE,
        MESH_CYLINDER,
        MESH_DATA,
        MESH_GRID,
        MESH_ICOSPHERE,
        MESH_MONKEY,
        MESH_PLANE,
        MESH_TORUS,
        MESH_UVSPHERE,
        META_BALL,
        META_CAPSULE,
        META_CUBE,
        META_DATA,
        META_ELLIPSOID,
        META_PLANE,
        MODIFIER,
        MODIFIER_DATA,
        MODIFIER_OFF,
        MODIFIER_ON,
        MOD_ARMATURE,
        MOD_ARRAY,
        MOD_BEVEL,
        MOD_BOOLEAN,
        MOD_BUILD,
        MOD_CAST,
        MOD_CLOTH,
        MOD_CURVE,
        MOD_DATA_TRANSFER,
        MOD_DECIM,
        MOD_DISPLACE,
        MOD_DYNAMICPAINT,
        MOD_EDGESPLIT,
        MOD_EXPLODE,
        MOD_FLUID,
        MOD_FLUIDSIM,
        MOD_HUE_SATURATION,
        MOD_INSTANCE,
        MOD_LATTICE,
        MOD_MASK,
        MOD_MESHDEFORM,
        MOD_MIRROR,
        MOD_MULTIRES,
        MOD_NOISE,
        MOD_NORMALEDIT,
        MOD_OCEAN,
        MOD_OFFSET,
        MOD_OPACITY,
        MOD_PARTICLES,
        MOD_PARTICLE_INSTANCE,
        MOD_PHYSICS,
        MOD_REMESH,
        MOD_SCREW,
        MOD_SHRINKWRAP,
        MOD_SIMPLEDEFORM,
        MOD_SIMPLIFY,
        MOD_SKIN,
        MOD_SMOOTH,
        MOD_SOFT,
        MOD_SOLIDIFY,
        MOD_SUBSURF,
        MOD_THICKNESS,
        MOD_TIME,
        MOD_TINT,
        MOD_TRIANGULATE,
        MOD_UVPROJECT,
        MOD_VERTEX_WEIGHT,
        MOD_WARP,
        MOD_WAVE,
        MOD_WIREFRAME,
        MONKEY,
        MOUSE_LMB,
        MOUSE_LMB_DRAG,
        MOUSE_MMB,
        MOUSE_MMB_DRAG,
        MOUSE_MOVE,
        MOUSE_RMB,
        MOUSE_RMB_DRAG,
        MUTE_IPO_OFF,
        MUTE_IPO_ON,
        NETWORK_DRIVE,
        NEWFOLDER,
        NEXT_KEYFRAME,
        NLA,
        NLA_PUSHDOWN,
        NOCURVE,
        NODE,
        NODETREE,
        NODE_COMPOSITING,
        NODE_CORNER,
        NODE_INSERT_OFF,
        NODE_INSERT_ON,
        NODE_MATERIAL,
        NODE_SEL,
        NODE_SIDE,
        NODE_TEXTURE,
        NODE_TOP,
        NONE,
        NORMALIZE_FCURVES,
        NORMALS_FACE,
        NORMALS_VERTEX,
        NORMALS_VERTEX_FACE,
        OBJECT_DATA,
        OBJECT_DATAMODE,
        OBJECT_HIDDEN,
        OBJECT_ORIGIN,
        ONIONSKIN_OFF,
        ONIONSKIN_ON,
        OPTIONS,
        ORIENTATION_CURSOR,
        ORIENTATION_GIMBAL,
        ORIENTATION_GLOBAL,
        ORIENTATION_LOCAL,
        ORIENTATION_NORMAL,
        ORIENTATION_VIEW,
        ORPHAN_DATA,
        OUTLINER,
        OUTLINER_COLLECTION,
        OUTLINER_DATA_ARMATURE,
        OUTLINER_DATA_CAMERA,
        OUTLINER_DATA_CURVE,
        OUTLINER_DATA_EMPTY,
        OUTLINER_DATA_FONT,
        OUTLINER_DATA_GP_LAYER,
        OUTLINER_DATA_GREASEPENCIL,
        OUTLINER_DATA_HAIR,
        OUTLINER_DATA_LATTICE,
        OUTLINER_DATA_LIGHT,
        OUTLINER_DATA_LIGHTPROBE,
        OUTLINER_DATA_MESH,
        OUTLINER_DATA_META,
        OUTLINER_DATA_POINTCLOUD,
        OUTLINER_DATA_SPEAKER,
        OUTLINER_DATA_SURFACE,
        OUTLINER_DATA_VOLUME,
        OUTLINER_OB_ARMATURE,
        OUTLINER_OB_CAMERA,
        OUTLINER_OB_CURVE,
        OUTLINER_OB_EMPTY,
        OUTLINER_OB_FONT,
        OUTLINER_OB_FORCE_FIELD,
        OUTLINER_OB_GREASEPENCIL,
        OUTLINER_OB_GROUP_INSTANCE,
        OUTLINER_OB_HAIR,
        OUTLINER_OB_IMAGE,
        OUTLINER_OB_LATTICE,
        OUTLINER_OB_LIGHT,
        OUTLINER_OB_LIGHTPROBE,
        OUTLINER_OB_MESH,
        OUTLINER_OB_META,
        OUTLINER_OB_POINTCLOUD,
        OUTLINER_OB_SPEAKER,
        OUTLINER_OB_SURFACE,
        OUTLINER_OB_VOLUME,
        OUTPUT,
        OVERLAY,
        PACKAGE,
        PANEL_CLOSE,
        PARTICLEMODE,
        PARTICLES,
        PARTICLE_DATA,
        PARTICLE_PATH,
        PARTICLE_POINT,
        PARTICLE_TIP,
        PASTEDOWN,
        PASTEFLIPDOWN,
        PASTEFLIPUP,
        PAUSE,
        PHYSICS,
        PINNED,
        PIVOT_ACTIVE,
        PIVOT_BOUNDBOX,
        PIVOT_CURSOR,
        PIVOT_INDIVIDUAL,
        PIVOT_MEDIAN,
        PLAY,
        PLAY_REVERSE,
        PLAY_SOUND,
        PLUGIN,
        PLUS,
        PMARKER,
        PMARKER_ACT,
        PMARKER_SEL,
        POINTCLOUD_DATA,
        POSE_HLT,
        PREFERENCES,
        PRESET,
        PRESET_NEW,
        PREVIEW_RANGE,
        PREV_KEYFRAME,
        PROPERTIES,
        PROP_CON,
        PROP_OFF,
        PROP_ON,
        PROP_PROJECTED,
        QUESTION,
        QUIT,
        RADIOBUT_OFF,
        RADIOBUT_ON,
        REC,
        RECOVER_LAST,
        REMOVE,
        RENDERLAYERS,
        RENDER_ANIMATION,
        RENDER_RESULT,
        RENDER_STILL,
        RESTRICT_COLOR_OFF,
        RESTRICT_COLOR_ON,
        RESTRICT_INSTANCED_OFF,
        RESTRICT_INSTANCED_ON,
        RESTRICT_RENDER_OFF,
        RESTRICT_RENDER_ON,
        RESTRICT_SELECT_OFF,
        RESTRICT_SELECT_ON,
        RESTRICT_VIEW_OFF,
        RESTRICT_VIEW_ON,
        REW,
        RIGHTARROW,
        RIGHTARROW_THIN,
        RIGID_BODY,
        RIGID_BODY_CONSTRAINT,
        RNA,
        RNA_ADD,
        RNDCURVE,
        ROOTCURVE,
        SCENE,
        SCENE_DATA,
        SCREEN_BACK,
        SCRIPT,
        SCRIPTPLUGINS,
        SCULPTMODE_HLT,
        SELECT_DIFFERENCE,
        SELECT_EXTEND,
        SELECT_INTERSECT,
        SELECT_SET,
        SELECT_SUBTRACT,
        SEQUENCE,
        SEQ_CHROMA_SCOPE,
        SEQ_HISTOGRAM,
        SEQ_LUMA_WAVEFORM,
        SEQ_PREVIEW,
        SEQ_SEQUENCER,
        SEQ_SPLITVIEW,
        SEQ_STRIP_DUPLICATE,
        SEQ_STRIP_META,
        SETTINGS,
        SHADERFX,
        SHADING_BBOX,
        SHADING_RENDERED,
        SHADING_SOLID,
        SHADING_TEXTURE,
        SHADING_WIRE,
        SHAPEKEY_DATA,
        SHARPCURVE,
        SHORTDISPLAY,
        SMALL_CAPS,
        SMALL_TRI_RIGHT_VEC,
        SMOOTHCURVE,
        SNAP_EDGE,
        SNAP_FACE,
        SNAP_FACE_CENTER,
        SNAP_GRID,
        SNAP_INCREMENT,
        SNAP_MIDPOINT,
        SNAP_NORMAL,
        SNAP_OFF,
        SNAP_ON,
        SNAP_PEEL_OBJECT,
        SNAP_PERPENDICULAR,
        SNAP_VERTEX,
        SNAP_VOLUME,
        SOLO_OFF,
        SOLO_ON,
        SORTALPHA,
        SORTBYEXT,
        SORTSIZE,
        SORTTIME,
        SORT_ASC,
        SORT_DESC,
        SOUND,
        SPEAKER,
        SPHERE,
        SPHERECURVE,
        STATUSBAR,
        STICKY_UVS_DISABLE,
        STICKY_UVS_LOC,
        STICKY_UVS_VERT,
        STRANDS,
        STROKE,
        STYLUS_PRESSURE,
        SURFACE_DATA,
        SURFACE_NCIRCLE,
        SURFACE_NCURVE,
        SURFACE_NCYLINDER,
        SURFACE_NSPHERE,
        SURFACE_NSURFACE,
        SURFACE_NTORUS,
        SYNTAX_OFF,
        SYNTAX_ON,
        SYSTEM,
        TEMP,
        TEXT,
        TEXTURE,
        TEXTURE_DATA,
        THREE_DOTS,
        TIME,
        TOOL_SETTINGS,
        TOPBAR,
        TPAINT_HLT,
        TRACKER,
        TRACKER_DATA,
        TRACKING,
        TRACKING_BACKWARDS,
        TRACKING_BACKWARDS_SINGLE,
        TRACKING_CLEAR_BACKWARDS,
        TRACKING_CLEAR_FORWARDS,
        TRACKING_FORWARDS,
        TRACKING_FORWARDS_SINGLE,
        TRACKING_REFINE_BACKWARDS,
        TRACKING_REFINE_FORWARDS,
        TRANSFORM_ORIGINS,
        TRASH,
        TRIA_DOWN,
        TRIA_DOWN_BAR,
        TRIA_LEFT,
        TRIA_LEFT_BAR,
        TRIA_RIGHT,
        TRIA_RIGHT_BAR,
        TRIA_UP,
        TRIA_UP_BAR,
        UGLYPACKAGE,
        UNDERLINE,
        UNLINKED,
        UNLOCKED,
        UNPINNED,
        URL,
        USER,
        UV,
        UV_DATA,
        UV_EDGESEL,
        UV_FACESEL,
        UV_ISLANDSEL,
        UV_SYNC_SELECT,
        UV_VERTEXSEL,
        VERTEXSEL,
        VIEW3D,
        VIEWZOOM,
        VIEW_CAMERA,
        VIEW_ORTHO,
        VIEW_PAN,
        VIEW_PERSPECTIVE,
        VIEW_ZOOM,
        VIS_SEL_00,
        VIS_SEL_01,
        VIS_SEL_10,
        VIS_SEL_11,
        VOLUME_DATA,
        VPAINT_HLT,
        WINDOW,
        WORDWRAP_OFF,
        WORDWRAP_ON,
        WORKSPACE,
        WORLD,
        WORLD_DATA,
        WPAINT_HLT,
        X,
        XRAY,
        ZOOM_ALL,
        ZOOM_IN,
        ZOOM_OUT,
        ZOOM_PREVIOUS,
        ZOOM_SELECTED,
    ]
